### ISSUE TITLE
Support for hot reloading of the dictionary

### ISSUE THREAD

**Issue by xml-js-dev** [justinwilaby/spellchecker-wasm#13]
Hi,

Thanks for this project by the way.

Would it be possible, given the current streaming architecture, to support reloading the dictionary with the same instance of the WASM spellchecker?

Common use cases : 

1. Remove a spelling from the dictionary
2. Add new spellings
3. Change the dictionary to another language

Thanks!

**Comment by justinwilaby** [comment]
Adding custom words to the dictionary is supported. Take a look at [this unit test](https://github.com/justinwilaby/spellchecker-wasm/blob/master/src/js/__tests__/SpellcheckerWasm.spec.ts#L68)

If you need to load another dictionary altogether, it's probably best to re-instantiate the Spellchecker and  point it to the new dictionary.

**Comment by xml-js-dev** [comment]
Thanks for the help.

I think re-instantiating is fine for swapping dictionaries. As for the writeToDictionary function, I'll submit a pull request with some documentation.
