### ISSUE TITLE
Crash when processing accented characters

### ISSUE THREAD

**Issue by xml-js-dev** [justinwilaby/spellchecker-wasm#14]
Hi,

I'm using a list with around 4200 misspelled words. The module crashes consistently on the 2234th entry when looping over them to check the spelling.

My code is adapted from one of your tests : 

```

function benchmark(spellchecker) {
    let lastResults;
    spellchecker.resultHandler = (results) => lastResults = results.map(result => result.term);
    let lookupTimes = [];
    let typoArr = typos.split(/[\n,]+/);
    let corrections = [];
    // for(let i = 0; i < typoArr.length; i++) {
     for(let i = 0; i < 2232; i++) {// Fails at 2233
        let word = typoArr[i];
        const t = performance.now();
        spellchecker.checkSpelling(word.toLowerCase());
        const s = performance.now();
        lookupTimes.push(s - t);
        corrections.push(...lastResults);
    }

    const totalTime = lookupTimes.reduce((previousValue, currentValue) => (previousValue += currentValue));
    console.log(`Total spellchecking time for ${lookupTimes.length} words : ${totalTime} ms and ${corrections.length} suggestions`);
    console.log(`Average lookup time: ${totalTime / lookupTimes.length} ms\n`);
}

```

The error in the console is :

Uncaught (in promise) RuntimeError: unreachable
    at wasm-function[95]:0x10b9a
    at wasm-function[67]:0x10864
    at wasm-function[73]:0x109fe
    at wasm-function[89]:0x10b67
    at wasm-function[74]:0x10a30
    at wasm-function[17]:0xb49f
    at wasm-function[76]:0x10a84
    at wasm-function[1]:0x1d58
    at wasm-function[68]:0x1088c
    at s.checkSpelling (webpack:///./lib/spellchecker-wasm/lib/browser/index.js?:229:91)
(anonymous) @ 0004a2c6-95:2
(anonymous) @ 0004a2c6-67:43
(anonymous) @ 0004a2c6-73:24
(anonymous) @ 0004a2c6-89:3
(anonymous) @ 0004a2c6-74:21
(anonymous) @ 0004a2c6-17:553
(anonymous) @ 0004a2c6-76:15
(anonymous) @ 0004a2c6-1:3554
(anonymous) @ 0004a2c6-68:17
checkSpelling @ index.js:229
benchmark @ spellchecker.js:40

List of words that I am using for benchmarking : 
[typos.txt](https://github.com/justinwilaby/spellchecker-wasm/files/4181964/typos.txt)

I've been able to reproduce this on 2 different systems, the crash point is the same.

Please let me know if you have any ideas as to what might be causing this.

Thank you.

**Comment by justinwilaby** [comment]
Does removing the 2234th entry resolve the issue? 

I've seen this when there is a parsing error due to whitespace chars or the amount of available memory in the wasm has been exceeded.

**Comment by xml-js-dev** [comment]
That was it; it choked-up on an accented character. Not sure why I didn't think of that, thanks!

Are there plans to support characters outside ASCII?

**Comment by justinwilaby** [comment]
This was designed to support all utf8 charsets. It seems like a bug if it's choking on an accented char. I'll look into this.

**Comment by xml-js-dev** [comment]
I used [this](https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines) list of words.

The first entry it choked on was : crèche
