### ISSUE TITLE
Differentiate between typos with no suggestions and correct spellings

### ISSUE THREAD

**Issue by xml-js-dev** [justinwilaby/spellchecker-wasm#16]
Hi,

Using the default dictionary, these two words return the same result : 

1. there
2. thereeeeee

Obviously, the first one is correct and the second one is a typo.

For words that are not in the provided dictionary, would it be possible to return a different value so that they can be distinguished?

Thanks!

**Comment by justinwilaby** [comment]
This is by design in order to maintain parity with the original SymSpell project. Changing this would mean a breaking change. 

 I would recommend differentiation between misspelled words using: 

```js
if (results.length === 1 && results[0].term === word) {
  return; 
}
```

**Comment by xml-js-dev** [comment]
I'm assuming the context for the above code is the resultHandler?

In that case, I see the same result for both using the browser API : 
there -->  0 undefined
thereeeeeee -->  0 undefined

My results handler : 

```
    this.spellcheckerWasm.resultHandler = (results) => {
        console.log(`${word} --> `, results.length, (results[0] || {}).term);
        suggestions = results.map(result => result.term);
    };
    this.spellcheckerWasm.checkSpelling(word);

```

**Comment by xml-js-dev** [comment]
Hi,

Have you had the chance to confirm this issue?

Thanks

**Comment by Devmacs** [comment]
I think this is a bug, since with includeUnknown: true, all correct words have a result :

```
 spellchecker.checkSpelling('eradicate', {
            includeUnknown: true,
            maxEditDistance: 2,
            verbosity: 3
        });
```

Returns : 
{
  count: 286780,
  distance: 1,
  term: 'eradicate'
}

But eradicate is certainly not an unknown.

**Comment by justinwilaby** [comment]
I remember dealing with this during the port from C#. From what I can tell, "unknown" simply means there was no suggestion. So either it was spelled correctly, or it exceeded the max edit distance.

I would default to to maintaining parity with the original. If the original shares the same behavior, and we still think this is a defect, a ticked should be opened there.

**Comment by wolfgarbe** [comment]
Here are the results of the C# SymSpell for "eradicate", maxEditdistance=2, Verbosity.All, includeUnknow=true

```
Dictionary: 82.765 words, 660.957 entries, edit distance=2 in 1122,5ms 55 MB
Type a work and hit enter key to get spelling suggestions:
eradicate
0,118 ms
eradicate 0 852.744
eradicated 1 349.318
eradicates 1 24.524
predicate 2 1.802.317
radiate 2 394.175
eradicator 2 34.055
6 suggestions
```
The reason for inclueUnknown is to allow for **automatic** spelling correction. With inclueUnknown=true terms not contained in the dictionary, and with no suggestions in the dictionary within the maximum edit distance will be still included in the output.

With includeUnknown=true, how do we distinguished whether 

1. a suggestion comes from the dictionary as a **spelling correction** (there is a dictionary term within maximum edit distance to the input term) or  
2. a suggestion is the original input term, which is an **unknown term** not contained in the dictionary (there is **no** dictionary term within maximum edit distance to the input term):
```
if (suggestions[0].distance>maxEditDistance) 
            Console.WriteLine("unknown input term") 
       else Console.WriteLine("known dictionary term or correction") 
```

**Comment by justinwilaby** [comment]
@wolfgarbe - Thank you for chiming in and for the snippet. 
@xml-js-dev - There is an open action item that resulted here. The `include_self` param in the `lookup` method is not exposed to the WASM binary. This was an oversight and is probably the reason for the `undefined` result. (`include_self` is `false` by default). I'll make that correction and raise a PR.
