### ISSUE TITLE
Exception when loading dictionary with non-ASCII characters

### ISSUE THREAD

**Issue by xml-js-dev** [justinwilaby/spellchecker-wasm#19]
Hi,

I get this error : 

RuntimeError: unreachable
    at wasm-function[93]:0x10b7f
    at wasm-function[67]:0x10862
    at wasm-function[73]:0x109fc
    at wasm-function[74]:0x10a2e
    at wasm-function[17]:0xb4d5
    at wasm-function[76]:0x10a82
    at wasm-function[3]:0x4784
    at d (webpack:///./lib/spellchecker-wasm-0.2.3/lib/browser/index.js?:178:45)
    at async s.prepareSpellchecker (webpack:///./lib/spellchecker-wasm-0.2.3/lib/browser/index.js?:182:13)
    at async Spellchecker.init (webpack:///./plugins/spellchecker/spellchecker.js?:121:3)

When I instantiate the spellchecker with this simple dictionary : 

the 23135851162
of 13151942776
and 12997637966
один 13151942773
такой 13151942771

Note that it works if the two Russian words are removed. I've tried several other languages (Arabic, French, Spanish, Greek, Portugese, ...) with similar results.

Thanks for any help.

**Comment by justinwilaby** [comment]
Looks like this is related to #14 . I'll check into this.
