### ISSUE TITLE
Execution in browser does not work

### ISSUE THREAD

**Issue by legose95** [justinwilaby/spellchecker-wasm#30]
I have tried to get the program running in the browser.
Therefore I used the code from the readme for the integration. 
Unfortunately I get the following js error: `import not found: SpellcheckerWasm `

The rebuilding works perfectly.

**Comment by Devmacs** [comment]
Hi,

Are you using any packaging system like Webpack or Rollup? Could you share your code?

Thanks

**Comment by legose95** [comment]
Hi, thank you for your answer. I am using webpack as a bundler (this is the template I am using for the website: https://github.com/rustwasm/create-wasm-app). Currently, I am able to compile it, but when running it I get this error: RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer.

**Comment by Devmacs** [comment]
Sorry for the delay.

Are you using Firefox or Chrome? Which version?

Are you trying to load the included dictionary or one of your own?

**Comment by justinwilaby** [comment]
fixed with #35
