### ISSUE TITLE
Instability of checkSpelling

### ISSUE THREAD

**Issue by Devmacs** [justinwilaby/spellchecker-wasm#32]
The spellchecker crashes on several words with the provided dictionaries. It also crashes with the new dictionaries from Symspell. I've reproduced these crashes with default initialization parameters and default checkSpelling parameters. The crashes are reproducible in both NodeJS and browser environments.

Here are a few problematic words and the dictionary that they cause crashes with :

US English dictionary : protégés
British English dictionary : appliquéing
French dictionary (Symspell-sourced) : adonises
German dictionary (Symspell-sourced) : adventist

I'll open a separate issue for the new dictionaries from Symspell (French, GErman, Italian, Hebrew, Russian).

**Comment by justinwilaby** [comment]
This was a fragment left in from the multi-byte grapheme support related to #7. Scouring these areas out should be just about complete.

**Comment by justinwilaby** [comment]
@Devmacs - Can you confirm that #34 fixes the issue?

**Comment by Devmacs** [comment]
@justinwilaby Seems to fix it, thanks!

I ran ~100k words against each dictionary and checked for crashes. None after your fix.

My word list is from : /usr/share/dict/words
