### ISSUE TITLE
Could this be used on the web?

### ISSUE THREAD

**Issue by iamtekeste** [justinwilaby/spellchecker-wasm#5]
I was wondering how hard it would be to port this to be used on the web/browser.
It would be interesting to load the dictionary files from the network.

**Comment by justinwilaby** [comment]
This could definitely be used for the web with a few adjustments. I kept this in mind while building the dictionary streaming feature and thought I would implement this soon.

**Comment by iamtekeste** [comment]
Awesome! Looking forward to it.

**Comment by justinwilaby** [comment]
Please see #6 
This is a WIP and needs testing but "should" work in the browser
