### ISSUE TITLE
Spellchecker locale isn't common American English

### ISSUE THREAD

**Issue by chrishuangcf** [justinwilaby/spellchecker-wasm#8]
The dictionary seems to be British English.  Spelling "color" would be flagged as "colour" instead.

**Comment by mmaietta** [comment]
+1

It seems like the current dictionary in this repo is up to date with SymSpell repo.  @chrishuangcf, I found this code though you could use to generate an en_US dictionary file:
https://github.com/wolfgarbe/SymSpell/issues/15#issuecomment-350243639
http://app.aspell.net/create?defaults=en_US

**Comment by justinwilaby** [comment]
I'm happy to include a reasonably complete American English dictionary. Any takers on creating one?
@mmaietta @chrishuangcf ?

**Comment by mmaietta** [comment]
I should be able to test it today on my fork and open a PR later today
