### ISSUE TITLE
Browser example does not work

### ISSUE THREAD

**Issue by xml-js-dev** [justinwilaby/spellchecker-wasm#9]
Hi,

I may be missing something, but in the initializeSpellchecker function, "spellchecker" is not defined.

Furthermore, when running your sample, I get this error (latest version of Chrome) : 

spellchecker.js:56 Uncaught TypeError: initializeSpellchecker.then is not a function

Thanks for any help

**Comment by justinwilaby** [comment]
You're right! The readme has typos. It should be something like this:
```js
const { SpellcheckerWasm }  = require('spellchecker-wasm');

async function initializeSpellchecker() {
    const wasm = await fetch('spellchecker-wasm/lib/spellchecker-wasm.wasm');
    const dictionary = await fetch('spellchecker-wasm/lib/frequency_dictionary_en_82_765.txt');
    const bigramLocation = await fetch('spellchecker-wasm/lib/frequency_bigramdictionary_en_243_342.txt'); // Optional

    const spellchecker = new SpellcheckerWasm();
    await spellchecker.prepareSpellchecker(wasm, dictionary, bigramLocation);
    return spellchecker;
}

initializeSpellchecker().then(spellchecker => {
    spellchecker.resultHandler = result => {
        ['tiss', 'gves', 'practiclly', 'instent', 'relevent', 'resuts'].forEach(word => spellchecker.checkSpelling(word));
        spellchecker.checkSpellingCompound('tiss cheks th entir sentance');
    }
    spellchecker.checkSpelling();
});
```

For a quick working example for web, please refer to [this unit test](https://github.com/justinwilaby/spellchecker-wasm/blob/master/src/js/__tests__/index.html).
In the meantime, I'll get the readme corrected.

**Comment by xml-js-dev** [comment]
Hi Justin, thanks for the quick turnaround.

Doesn't : 
    require('spellchecker-wasm');

imply NodeJS? 

I'm trying to get this working without installing it through Node, so I'm using a local copy in a ./lib folder. I n this case, what's the entry point for an ES6-like import (or Webpack import)?

Thanks!

**Comment by justinwilaby** [comment]
I did just that in [this unit test](https://github.com/justinwilaby/spellchecker-wasm/blob/master/src/js/__tests__/index.html)

The important bits are:

```js
<script>
    // Testing purposes only. Normally, we'd let webpack define this
    window.exports = {}
</script>
<script src="path/to/local/lib/browser/index.js"></script>
<script>
const {SpellcheckerWasm} = exports['spellchecker-wasm'];
// do all the stuffs here.
</script>
``` 

I hope that helps!

**Comment by xml-js-dev** [comment]
Sorry, I had glossed over the index.js import. That fixed it, thanks!

**Comment by tooolbox** [comment]
https://github.com/justinwilaby/spellchecker-wasm/issues/9#issuecomment-583112419 was required to get this working in the browser.  Example in readme doesn't work because index.js doesn't actually `export` per ES module semantics.
